### ISSUE TITLE
Controller gone?????

### ISSUE THREAD

**Issue by Mydoge** [iGBAEmu/EclipseIssues#10]
When I was trying to play my games when I clicked on one, there wasn’t any controller on the screen pls help

**Comment by Shugabuga** [comment]
Can you tell me what device you are on, what web browser you are using, and what OS version it is running?

I would go into Settings, then disable Desktop Mode. This hides the controller. Let me know if that works (it should).

**Comment by Shugabuga** [comment]
Okay, we have done more research on this issue. For some reason, Eclipse thought some iOS devices were actually desktop, not mobile devices. This caused Eclipse to enable Desktop Mode (a feature that hides the controllers) by default.

Eclipse 1.0.8 will fix this bug.

**Comment by Mydoge** [comment]
K thx

**Comment by Mydoge** [comment]
I am using iPhone 8 Plus, ios 11.3, safari
