### ISSUE TITLE
White screen 

### ISSUE THREAD

**Issue by Gamboy6** [iGBAEmu/EclipseIssues#100]
Problem : 
I wanted to play dragon ball z buu’s fury on my phone so I decided to use eclipse but when I downloaded the ROM and uploaded it to eclipse it just gave me a white screen. After 1 or 2 mins the game boy symbol shows but after that nothing I waited for 5 mins. I tried it from dropbox also and it gave me the same thing. I would appreciate it if you could troubleshoot the problem. 

![30D960F0-1FA4-4AAA-8972-1E871E080EB6](https://user-images.githubusercontent.com/64849087/81074726-6b628700-8eb7-11ea-8127-cee3b538ce49.jpeg)

web browser: safari , device: iPhone XS, and I added eclipse to my home screen from the website.

**Comment by N-Games** [comment]
Don't download roms

**Comment by Gamboy6** [comment]
Is there a another way to play without downloading?

**Comment by Shugabuga** [comment]
How does the ROM work in other emulators?

**Comment by Gamboy6** [comment]
I don’t know of any other emulators

**Comment by magnetardev** [comment]
See #201
