### ISSUE TITLE
I can not download games

### ISSUE THREAD

**Issue by GBA1233** [iGBAEmu/EclipseIssues#104]
![B718E0DD-90FE-4CBB-A876-8017569FF2AD](https://user-images.githubusercontent.com/65154637/81534411-aad61b00-9370-11ea-8f7b-96dd4ce814c8.jpeg)
When I try and download a game an error pops up that says daily limit for unauthenticated use exceeded
Hold on a game and press download

I am using an Ipad air 2 and the game is Pokemon fire red

**Comment by magnetardev** [comment]
This was a fluke, you can't download games from Google Drive. The UI now reflects this as v2.2.
