### ISSUE TITLE
Save states don't work in iOS

### ISSUE THREAD

**Issue by N-Games** [iGBAEmu/EclipseIssues#107]
Every game/emulator core that Eclipse has/runs can't make a save state in iOS. It says that the save file is to big. And sometimes you can save, but then it won't save. Idk what is going on here. It works fine in my Android device
# How to Reproduce
By making a save state

# Device Information
iPhone 8 iOS 13.4.1 Jailed

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)
DOMException { line: 11, column: 712954, sourceURL: "https://eclipseemu.me/play/js/app.js" }

**Comment by Shugabuga** [comment]
What you may see as save states is likely our data export system (.eclipse backup), which is known to be buggy in 2.0. Eclipse currently doesn't export save files that can be imported/exported from other emulators.
