### ISSUE TITLE
Can’t see downloaded games? 

### ISSUE THREAD

**Issue by perkysrig** [iGBAEmu/EclipseIssues#108]
I’m downloading old gameboy and ds games through drive, worked for the first 4. Now I can get to the entire process through downloading them into my drive (I see them there) but when I go into eclipse into upload it only shows me the first 3 I’ve downloaded. Don’t understand why I can’t see anything else?

**Comment by Shugabuga** [comment]
- Eclipse does't support DS games. They won't show up at all.

- Eclipse don't let you load GBA games inside of ZIP files. Extract the file from any ZIP file, upload the extracted .gb/.gbc/.gba file to Drive and try again.

Eclipse hides any unsupported file types in its Drive picker.

**Comment by israelpgjm** [comment]
> I’m downloading old gameboy and ds games through drive, worked for the first 4. Now I can get to the entire process through downloading them into my drive (I see them there) but when I go into eclipse into upload it only shows me the first 3 I’ve downloaded. Don’t understand why I can’t see anything else?



> * Eclipse does't support DS games. They won't show up at all.
> * Eclipse don't let you load GBA games inside of ZIP files. Extract the file from any ZIP file, upload the extracted .gb/.gbc/.gba file to Drive and try again.
> 
> Eclipse hides any unsupported file types in its Drive picker.
