### ISSUE TITLE
Games Not Loading

### ISSUE THREAD

**Issue by BeastMode444** [iGBAEmu/EclipseIssues#115]
Whenever I try to add games on iOS, it shows the buttons as if I am about to play the game, but it only shows a black screen (and I tried this multiple times (I’d say about 5-10 times) for about 5 minutes each).

I pressed the plus sign at the top right corner, pressed upload, then browse, then I pressed the game I wanted to play, and the “controller” showed up on my screen, but it was all black. I was trying to play The Legend of Zelda, if any of this helps.

![E856B1D7-B907-4E8D-AB31-5BC90BCF9DEE](https://user-images.githubusercontent.com/66500220/83931421-80019b80-a751-11ea-9371-a9dd70d119aa.png)

I am currently on iOS 13.3.1 and am using a 12.9 inch, 3rd generation iPad Pro if that helps.

**Comment by magnetardev** [comment]
Make sure you're uploading an actual ROM (e.g. Zelda.gba) instead of an archive (e.g. Zelda.zip)
