### ISSUE TITLE
Games not loading error message

### ISSUE THREAD

**Issue by YaBoyBroski** [iGBAEmu/EclipseIssues#116]
Whenever I try to load a game it loads up, I press start to start the game and then immediately it brings up a message in the actual game itself saying “the internal battery has run dry. The game CAN be played.” That’s literally exactly what it says but then it doesn’t let me continue past that message. I’ve tried multiple different sources for rom downloads and my battery is fine last I checked I mean my phone stays charged pretty much all day. 

I’m using an iPhone 6S on iOS 13.1.2 

(Please describe your issue or feature request, in detail, here.)

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by magnetardev** [comment]
Assuming this was an issue with controls, as Pokemon games that display that message can be played -- as I have experienced multiple times.

Update iOS, iOS 13.1 simply broke our controls but was fixed in future iOSs.
