### ISSUE TITLE
Stuck on desktop mode (even with disabled)

### ISSUE THREAD

**Issue by Mydoge** [iGBAEmu/EclipseIssues#12]
When I get on a game on esclipse it saids desktop mode enabled! And desktop mode is disabled! Pls help

**Comment by Mydoge** [comment]
iPhone 8 Plus, safari, iOS 11.3

And I don’t know what the JavaScript console is

**Comment by Shugabuga** [comment]
Okay. Make sure Eclipse is up to date, then go to Settings and tap on the navbar (with the word "Settings") five times to enable Debug Mode. Go into the debugger menu, and try tapping on the "Desktop Mode" button. That should run `desktopModeTing()`.

Let me know if that helps.

**Comment by Mydoge** [comment]
Nope didn’t help i tapped the button in blue text and it was still enabled

**Comment by Shugabuga** [comment]
Is this bug still an issue? I don't think the team was able to replicate this.

**Comment by Majinsmash** [comment]
Closing because stale issue. If it is still an issue, feel free to reopen.
