### ISSUE TITLE
Cannot download data for an individual game

### ISSUE THREAD

**Issue by BaconWrappedShrimpWithEyes** [iGBAEmu/EclipseIssues#132]
# Description

When a game is in one's library, the download save option returns the error:
!["There is no save data for this game](https://drive.google.com/uc?export=view&id=1wIr9DLxHkcoxWFV4Ci-8kZfxD7-Ls5ie)
independent of whether or not Eclipse has any save data for the given game.

# How to Reproduce

1. Use Google Drive, Dropbox, or add via link to add a game to Eclipse such that the ROM stays in your library
2. Play the game and save as you would if your intention was to return to the game. Upon return to the same game, it should be possible to return to that save.
3. In tile view, tap and hold the icon for the game, then tap "Save" —> "Download." 

# Device Information

Error occurs on my iPhone XR running 13.5 with Eclipse on a Safari-based web clip over SSL encryption. This is an issue that has been pointed out by many separate Eclipse users in the Zenith Discord server.

**Comment by Ausery** [comment]
having the same issue

**Comment by Shugabuga** [comment]
Saving is all kinds of broken. When v2.2 comes out, can you please test this again? We moved to `.sav` and I am pretty sure this got fixed.

**Comment by BaconWrappedShrimpWithEyes** [comment]
Absolutely, Shuga.

**Comment by BaconWrappedShrimpWithEyes** [comment]
Tested - fixed in 2.2
