### ISSUE TITLE
Saving game

### ISSUE THREAD

**Issue by josejrg10** [iGBAEmu/EclipseIssues#137]
# Description
I downloaded a new game megaman battle network 5 
I try to same In game but it tells me the saved has failed. I can’t save the game In the megaman game and I also tried it on an alternative version. 
All my other old Pokémon games and yugioh games save in game but I would really like to start my megaman games. Wondering what bug that must be
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by magnetardev** [comment]
Sounds like what's happening in #169 is happening here. Closing to make a unified place for future discussion.
