### ISSUE TITLE
AB buttons don’t work

### ISSUE THREAD

**Issue by abdulismail95** [iGBAEmu/EclipseIssues#145]
Look like AB button don’t work but start stop select does. can’t start pokemon.

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information
IOS 13.1.2
(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by magnetardev** [comment]
No fix other than updating iOS. iOS 13.1 broke how we handled controls, later versions fixed it.
