### ISSUE TITLE
Error when I link my cloud account to eclipse game list

### ISSUE THREAD

**Issue by al24bi** [iGBAEmu/EclipseIssues#146]
![D319494C-390E-4E60-9456-A84AE08003DF](https://user-images.githubusercontent.com/68809557/88477018-d95d9e00-cf3c-11ea-90c4-54535c376099.png)
# Description

Hi I get this error (attached pic) when I try to login in google drive to connect my cloud to eclipse app and browse my gba roms.
And if I try to use my Dropbox account it doesn’t link my game saved on Dropbox to eclipse.

![084FEB12-4041-435B-9735-53673EADF490](https://user-images.githubusercontent.com/68809557/88477095-96e89100-cf3d-11ea-95a7-dd43798096ab.jpeg)
![36A73399-90CD-42A2-9665-DDFC12AD1417](https://user-images.githubusercontent.com/68809557/88477097-98b25480-cf3d-11ea-879e-b57f6927f4c1.png)

# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | false | 
| Languages | it | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Shugabuga** [comment]
This isn't a bug. Google Drive requires that all connections be done securely, but you didn't use the HTTPS (secure) version of Eclipse. You're going to need to reinstall Eclipse from https://eclipseemu.me/play/ to resolve this, assuming this is your first time playing.
