### ISSUE TITLE
Can’t see games 

### ISSUE THREAD

**Issue by NbaNo-Cap** [iGBAEmu/EclipseIssues#155]
# Description to play a game I have to go to my files 
*Please describe your issue here.* it’s not letting me see the games in card form or list 
# Device Information iPhone XR(red) 
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-us | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by magnetardev** [comment]
This isn't a bug, it's just not designed well. "Adding" a game via files just loads it into the emulator. Saving works just fine.

This has been addressed in a future update by making it an actual feature. No ETA on release yet.
