### ISSUE TITLE
I don’t have a sound in games on iPad 

### ISSUE THREAD

**Issue by ankhrenan** [iGBAEmu/EclipseIssues#156]
# Description
*Please describe your issue here.*
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | Desktop | 
| User Agent | Mozilla/5.0 (Macintosh- Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | pt | 
| Vendor | Apple Computer, Inc. | 
 | Platform | MacIntel |

**Comment by ankhrenan** [comment]
I’m don’t have any sound using this app in iPad, I test many games and doesn’t work, why fix it?

**Comment by magnetardev** [comment]
Fixed in v2.2, which has been released.
