### ISSUE TITLE
Controller Buttons Are Too Small

### ISSUE THREAD

**Issue by TURDTSUMAKI** [iGBAEmu/EclipseIssues#168]
# controls too small and super congested.not that responsive.these problems happen in every iPad.pls fix :)

# How to just try to play street fighter or any game on an iPad.

# Device Information
iPad Air 2
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by magnetardev** [comment]
See #138
