### ISSUE TITLE
Do external controllers like the ones we use for PUBG work in this emulator?

### ISSUE THREAD

**Issue by velvetrevolverr** [iGBAEmu/EclipseIssues#170]
# Description

(Please describe your issue or feature request, in detail, here.)

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by magnetardev** [comment]
*Taken from our Discord Server*

If you are on iOS 14 (or greater), yes, you can use bluetooth controllers in Eclipse. Note: our support of controllers is still in *beta*, things like analog sticks will not work! Also, your controller needs to be either a MiFi, PS4, or Xbox One controller (restricted by iOS).

__To setup a controller:__
- Connect the controller to your iOS device (see https://support.apple.com/en-us/HT210414#ios)
- Open Eclipse
- Go to Settings and scroll down to controls
- You should see your controller listed
- Tap on the controller listing
- Go through each of the buttons and press a button on your controller to bind it.
- Enjoy!
