### ISSUE TITLE
Controllers 

### ISSUE THREAD

**Issue by Jermaine2424** [iGBAEmu/EclipseIssues#172]
Does PS4 controllers work on the iPhone because it works on iPad when connected I just want to know how could you guys help me

**Comment by magnetardev** [comment]
*Taken from our Discord Server*

If you are on iOS 14 (or greater), yes, you can use bluetooth controllers in Eclipse. Note: our support of controllers is still in *beta*, things like analog sticks will not work! Also, your controller needs to be either a MiFi, PS4, or Xbox One controller (restricted by iOS).

__To setup a controller:__
- Connect the controller to your iOS device (see https://support.apple.com/en-us/HT210414#ios)
- Open Eclipse
- Go to Settings and scroll down to controls
- You should see your controller listed
- Tap on the controller listing
- Go through each of the buttons and press a button on your controller to bind it.
- Enjoy!
