### ISSUE TITLE
New Update A/B Buttons iphone issue

### ISSUE THREAD

**Issue by Captcorderoy** [iGBAEmu/EclipseIssues#177]
The latest update solved the sound issue which is great :) but created a issue where when a user is trying to simultaneously push the A+B together or hold them - the emulator is unresponsive or cant detect the command. Please look into this and fix it , it was responsive before the latest update, also unrelated - im experiencing more lag during this update.

Devices: ipad mini, iphone 7plus, iphone X -Lastest ios

**Comment by magnetardev** [comment]
The face buttons and d-pad are a joystick, technically. To press A and B at the same time, go in between the two buttons:

```
   B
A [Here]
```

Lag is probably as a result of audio finally working.
