### ISSUE TITLE
Not saving 

### ISSUE THREAD

**Issue by itscjunknown** [iGBAEmu/EclipseIssues#178]
# Description
*Please describe your issue here.*
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | false | 
| Auto-Save Rate| 30000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | true | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.2.0 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone | 
It won’t save my game

**Comment by magnetardev** [comment]
Vauge. No game or system provided.
