### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by valorjunkie** [iGBAEmu/EclipseIssues#179]
There is no audio coming through for any games. 
iPhone iOS 13
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 30000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.2.0 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by h57758** [comment]
On a iPad i have audio check so that the switch on your phone is not red if it is red then no audio

**Comment by magnetardev** [comment]
Make sure you have ringer on and that any pre-v2.2 cache has been cleared. (Settings -> Clear Cache).
