### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by Bananajuicyy** [iGBAEmu/EclipseIssues#187]
# Description
*Please describe your issue here.*
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 30000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.2.0 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | de-de | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Bananajuicyy** [comment]
i cant see my game in the library

**Comment by rossyross22** [comment]
Emulator won’t even open up and after the first time I have to take it off home screen and do the process again

**Comment by magnetardev** [comment]
This isn't a bug, it's just not designed well. "Adding" a game via files just loads it into the emulator. Saving works just fine.
