### ISSUE TITLE
iNoBounce makes D-Pad Right stay pressed

### ISSUE THREAD

**Issue by BaconWrappedShrimpWithEyes** [iGBAEmu/EclipseIssues#19]
# Description

As of the latest update of Eclipse (which added iNoBounce support), there seems to be a sticky-tap effect occurring with some buttons. This is NOT likely the fault of iNoBounce as we first believed it to be, as it can happen in the MD skin, though it started when the iNoBounce update was set in place. I did not change my keyboard bindings after the update, they were set the same way before and after the update.

# How to Reproduce

Set Button to D in Keyboard Bindings

# Device Information

iPhone SE 16GB, iOS 11.3
Recreated by turning off desktop mode on 2015 13" macbook pro with retina display

**Comment by Shugabuga** [comment]
Thanks for opening an issue, but can you please fill out some more information on how to reproduce the bug, and some information on your device?
This can help with debugging.

**Comment by BaconWrappedShrimpWithEyes** [comment]
Where do I do that?

**Comment by Shugabuga** [comment]
Just edit your original post or reply with any information you have that can help us reproduce it.

**Comment by Majinsmash** [comment]
iNoBounce is no longer in Eclipse, so this shouldn't be an issue anymore. If it is, feel free to reopen.
