### ISSUE TITLE
Error que te quita el progreso

### ISSUE THREAD

**Issue by elpepe987** [iGBAEmu/EclipseIssues#195]
Al apagarse el celular el juego se traba y se tiene se borrar la pestaña y volver a entrar lo que causa que se borre el progreso no guardado

**Comment by magnetardev** [comment]
Usando Google Translate, espere una mala traducción.

Esto se debe a que Safari está intentando liberar memoria, por lo que está recargando la página. La mejor solución es agregar Eclipse a la pantalla de inicio (botón Compartir -> Agregar a la pantalla de inicio). Aparte de eso, esto no es algo que podamos solucionar.
