### ISSUE TITLE
Controls buggy/non-functional

### ISSUE THREAD

**Issue by jobor12487** [iGBAEmu/EclipseIssues#198]
# Description
Left and right (possibly up and down) d-pad not working, A & B buttons not working (not in a very playable sense), start & select button also not really working

# How to Reproduce
Go on google chrome on an mobile device (I was using an ipad), go into a game, flip the screen vertical then diagonal, exit to main menu then go back into a game, the buttons will be very odd and may not respond when you press them now

# Device Information
iPad (6th gen)
Software version 13.7
Model #MR7J2LL/A
Serial #DMPYQJ2YJF8M

**Comment by magnetardev** [comment]
See #45
