### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by b0ring123** [iGBAEmu/EclipseIssues#20]
# Description

(When ever I start up my mother 3 rom for eclipse it just gives me a white screen and I can wait as long as I like for the game to start but it won’t.)

# How to Reproduce

(I’m not sure how to reproduce this issue)

# Device Information

(I have an iPhone 8 With IOS 11.4.1)

**Comment by Shugabuga** [comment]
The ROM for Mother 3 is 30+ MB. That takes time to download and it takes time for the core to initialize the game. How long have you waited?

**Comment by b0ring123** [comment]
I’ve waited like one minute and 30 seconds

**Comment by Shugabuga** [comment]
What are your Internet speeds, and what device are you on?

I cannot reproduce this big.

**Comment by b0ring123** [comment]
My internet speed is about 12.5 Mbps per download and 6.74 Mbps per upload.

And I use an iPhone 8

**Comment by Shugabuga** [comment]
We just updated Eclipse to 2.0.x. Does this bug still exist?

**Comment by b0ring123** [comment]
I don’t think I updated to version 2.0

**Comment by Shugabuga** [comment]
Can I see a screenshot of Eclipse? I can see if it updated or not.

**Comment by b0ring123** [comment]
How do I update the eclipse emulator?
