### ISSUE TITLE
Allow category header theming in OpenSkin

### ISSUE THREAD

**Issue by realSmushyTaco** [iGBAEmu/EclipseIssues#21]
# Description
If you select the dark mode skin and go to a repo list where the category is named is still white.
(Please describe your issue or feature request, in detail, here.)

# How to Reproduce
Go into dark mode.
(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)
Select the dark mode skin.
# Device Information
iPhone 6 Plus 128 GB iOS 11.4.1 downloaded Eclipse.
(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by Majinsmash** [comment]
Fixed in v2.1
