### ISSUE TITLE
Buttons Enhancement

### ISSUE THREAD

**Issue by realSmushyTaco** [iGBAEmu/EclipseIssues#22]
# Description
Make it so when we click a button the button you click gets a little dark tint to indicate that you clicked it and to simulate it being pressed.
(Please describe your issue or feature request, in detail, here.)

# Device Information
iPhone 6 Plus 128 GB iOS 11.4.1 Eclipse installed
(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by Shugabuga** [comment]
What buttons? The buttons for each emulator/game entry?

Many of the buttons already have this behavior, but having them for emulators and game entry would be beneficial.

**Comment by SmushyRepo** [comment]
The L, R, Arrow, B, A, Menu, Select, and Start buttons.

**Comment by Shugabuga** [comment]
Oh yeah, those don't have that either.

Nice catch.

**Comment by SmushyRepo** [comment]
Can't wait to see this in the future :)

**Comment by JeffResc** [comment]
I also had this idea. Sometimes I press a button and nothing happens on screen so I’d be helpful to know if either a.) I missed the button, b.) the emulator just didn’t get the button for some reason or c.) that button does nothing at this point in the game. Thanks!

**Comment by SmushyRepo** [comment]
1) If this was a thing it would give a message if you clicked the body of the emulator where there were no buttons which seems a bit annoying and useless.

2) If the emulator didn't notice you clicked the button then how would the emulator tell you that?

3) You'll know if the button does nothing because nothing would happen if you clicked it.

**Comment by JeffResc** [comment]
I’m not saying it needs to say when the body of the emulator is pressed. I’m just agreeing that a visual feedback would be nice as I myself would be able to tell what happened

**Comment by SmushyRepo** [comment]
Oh ok. My bad I misunderstood what you were trying to say.

**Comment by Majinsmash** [comment]
Added indication on buttons that are actually pressed. Not visible on the D-Pad or face buttons because that is using NippleJS.
