### ISSUE TITLE
Legacy Mode Automatically Disables Itself

### ISSUE THREAD

**Issue by JeffResc** [iGBAEmu/EclipseIssues#24]
# Description
Legacy mode automatically disables itself upon closing the app

# How to Reproduce

Set legacy mode to on, close the app, come back to the app and it will be off.

[View The Video on Google Photos Here](https://photos.app.goo.gl/KuveZYFXAvnF8ufQ7).

# Device Information
## States
Audio Enabled: false
Auto-Save Enabled: true
Current Skin Set?: true
Desktop Mode Enabled: false
Full Screen Enabled: false
Game List Initialized?: true
Repo List Initialized?: true
Skin List Initialized?: true
Set-Up Successful?: 2.0.2
## Device
Device (F7): iOS iPhone
User Agent: Mozilla/5.0 (iPhone- CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
Do Not Track: 0
Cookies Enabled?: true
ServiceWorker Support: true
Languages: en-US
Vendor: Apple Computer, Inc.
Platform: iPhone

**Comment by magnetardev** [comment]
Since legacy mode isn't exactly a feature anymore, this should be fixed lol.
