### ISSUE TITLE
Add repo page stuck at white loading image.

### ISSUE THREAD

**Issue by HippoInWindow20** [iGBAEmu/EclipseIssues#25]
# Description

The add game page would stuck at white loading image without anything usable.

# How to Reproduce

1. Go to eclipseemu.me/play
2. Add page as bookmark in Safari.
3. Open page via the bookmark.
4. Click plus.
5. Choose Game Hub.
6. It would be stuck at a white loading image.

# Device Information

Browser: Safari
Device: iPhone 6s iOS 12.0
Eclipse installation: Through Add to home screen.

**Comment by Shugabuga** [comment]
Do you have any games in your Google Drive?

**Comment by HippoInWindow20** [comment]
No.

**Comment by Shugabuga** [comment]
Ensure Eclipse is on `2.0.6` (you can check in Eclipse's settings). Once it is, let me know if you are still having issues.

**Comment by HippoInWindow20** [comment]
Thanks! It’s fixed now.

**Comment by Shugabuga** [comment]
That's great to hear! Closing...
