### ISSUE TITLE
Files idea

### ISSUE THREAD

**Issue by realSmushyTaco** [iGBAEmu/EclipseIssues#26]
# Description
Main Idea: A way to download ROMs to your device.

Requirements: Downloading Eclipse instead of using the website version (I only wrote this because I don't think the website version can use the Files app.).

Description: When you first set up the Eclipse application a file named "Eclipse" will be made in the "Files" application automatically on your iDevice (If this isn't possible it would ask you for permission to do so and if you're updating to a new version that adds this it would do the same thing as if you were first setting up Eclipse.). After this whenever you add a repository to Eclipse a folder named the repository address will be made. Whenever you add a ROM it would download it under the repository file made in the Files app. In the settings of Eclipse this feature would be able to be toggled on and off.

# Device Information
iPhone 6 Plus 128 GB iOS 11.4.1 with Eclipse installed on my iDevice.

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by Shugabuga** [comment]
Pro tip: web apps can browse Files.app via the upload feature and games can be downloaded with the Download function in the tap-hold/right-click context menu.
