### ISSUE TITLE
Start, Select, and Menu will not appear on iPad Air 2

### ISSUE THREAD

**Issue by CamVSGaming** [iGBAEmu/EclipseIssues#28]
# Description

For some reason, the bottom controls (Start, Select, Menu) will not appear. As shown in the picture attached.
![c68fe351-cdfb-483e-8dc3-42b713a00881](https://user-images.githubusercontent.com/42359353/45498944-48ff8100-b749-11e8-8e5c-8c101f4812dc.png)

# How to Reproduce

Use an iPad Air 2, start up a game and Start, Select and Menu will not pop up on the bottom of the screen.

# Device Information

iPad Air 2

**Comment by Shugabuga** [comment]
What happens if you try to enable Legacy Mode in Eclipse's settings?

**Comment by CamVSGaming** [comment]
I’m Sorry, but where can I enable Legacy Mode?

**Comment by Shugabuga** [comment]
Eclipse -> Settings (Gear icon) -> Legacy Mode

Make sure it is on.

**Comment by CamVSGaming** [comment]
Can’t seem to find it...
![39a78432-8b96-4171-b37a-93177d19bb4a](https://user-images.githubusercontent.com/42359353/45620737-de518c80-ba4b-11e8-9abc-44fae29284a9.png)

**Comment by magnetardev** [comment]
This shouldn't be an issue anymore.
