### ISSUE TITLE
Unresponsive buttons

### ISSUE THREAD

**Issue by lchen533** [iGBAEmu/EclipseIssues#29]
# Description
Certain keys on the emulator are unresponsive, such as the LR keys, A,B,Start, and Select. Tried the fix buttons button in the menu, but it had no effect on the buttons.

# Device Information
iPhone 7+ running iOS 12.0

**Comment by harper-coding-stuff** [comment]
I'm having the same issues. iPhone XR, iOS 12.1.4 the D-Pad is fine and so are Select and Start, but the LRAB buttons don't react, type twice and generally act sticky. Perhaps making them bigger would be a fix??

**Comment by Majinsmash** [comment]
Fixed in v2.1
