### ISSUE TITLE
Statusbar for iOS 11 fix

### ISSUE THREAD

**Issue by JosephShenton** [iGBAEmu/EclipseIssues#3]
To bring back the coloured status bar on iOS 11 do the following

```
ADD THIS META TAG

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui, viewport-fit=cover">


ADD THIS STYLE

body {
	height: calc(100% + 20px);
}
```

**Comment by JosephShenton** [comment]
Then just add your normal statusbar colour for statusbar-overlay

**Comment by Shugabuga** [comment]
Pushed the meta tag changes, but the body style will break on anything that isn't an iOS web clip (so it wasn't added).
