### ISSUE TITLE
Real Time Clock

### ISSUE THREAD

**Issue by edwinjimenez19** [iGBAEmu/EclipseIssues#306]
# Description

It would be a great feature to a add a real time clock. I’m playing a Pokémon red hack. To unlock all the catchable Pokémon the game
Requires to use a real time clock. This allows you to to catch different Pokémon at different times of the day/night.

# How to Reproduce

# Device Information

( Im using an iPhone X. My browser is Safari. I’m using the latest installment of eclipse x

**Comment by magnetardev** [comment]
Duplicate of #98
