### ISSUE TITLE
The games don’t allow for a second upload

### ISSUE THREAD

**Issue by papapasta** [iGBAEmu/EclipseIssues#34]
# Description
*Please describe your issue here.*
# Device Information
## States
Audio Enabled: true 
Auto-Save Enabled: true 
Current Skin Set?: true 
Desktop Mode Enabled: false 
Full Screen Enabled: false 
Game List Initialized?: true 
Repo List Initialized?: true 

Skin List Initialized?: true 
Set-Up Successful?: 2.0.6 
## Device
Device (F7): iOS iPad  
User Agent: Mozilla/5.0 (iPad- CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1 
Do Not Track: Not Set 
Cookies Enabled?: true 
ServiceWorker Support: true 
Languages: en-US 
Vendor: Apple Computer, Inc. 
Platform: iPad 
The problem is, that whenever I try to re upload a game, it just doesn’t come up 
I also put it onto Dropbox and put it in eclipse, but it still doesn’t remember the save

**Comment by magnetardev** [comment]
Should've been addressed in v2.1.8
