### ISSUE TITLE
White screen when loading rom

### ISSUE THREAD

**Issue by WitherTech** [iGBAEmu/EclipseIssues#35]
# Description
I try to load Pokémon ruby rom, but the emulator shows a white screen
# Device Information
## States
Audio Enabled: true 
Auto-Save Enabled: true 
Current Skin Set?: true 
Desktop Mode Enabled: false 
Full Screen Enabled: false 
Game List Initialized?: true 
Repo List Initialized?: true 
Skin List Initialized?: true 
Set-Up Successful?: 2.0.6 
## Device
Device (F7): iOS iPhone  
User Agent: Mozilla/5.0 (iPhone- CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1 
Do Not Track: 1 
Cookies Enabled?: true 
ServiceWorker Support: true 
Languages: en-US 
Vendor: Apple Computer, Inc. 
Platform: iPhone

**Comment by WitherTech** [comment]
![E8295986-ED5F-41E9-9584-6051975FAE17](https://user-images.githubusercontent.com/39203202/56686759-547d3800-669a-11e9-85fa-c6a11815d5e9.png)

**Comment by Shugabuga** [comment]
Where did you load the ROM from?

**Comment by WitherTech** [comment]
Google drive

**Comment by WitherTech** [comment]
All my other roms say “rom image too small”

**Comment by WitherTech** [comment]
This is the only emulator I can use right now because of the string of revokes going around

**Comment by Shugabuga** [comment]
@WitherTech Don't use Google Drive until 3.0.0 drops. It's a known issue and we have a different implementation in place in 3.0.0 to (hopefully) prevent this in the future.

We recommend using Dropbox for the meantime. It should work a lot better.

**Comment by WitherTech** [comment]
It won’t let me login with google on dropbox

**Comment by WitherTech** [comment]
I just tried a game from a repo and white screen

**Comment by WitherTech** [comment]
I added it with a link to the rom on Dropbox and it worked
