### ISSUE TITLE
Sound not working at all

### ISSUE THREAD

**Issue by orangehead7** [iGBAEmu/EclipseIssues#36]
# Description

(Please describe your issue or feature request, in detail, here.)

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by magnetardev** [comment]
Can you please add some device info? Can’t exactly fix anything without knowing at least that.

**Comment by Shugabuga** [comment]
As @magnetardev said, please fill in all of the above blanks. Is your ringer on? What version of iOS are you on? What systems don't support audio?

**Comment by GoldwinXS** [comment]
description: no audio on iOS 13 on both iPad and iPhone 
how to reproduce: simply running any ROM should do. ROMs tested were: Pokemon Blue (GB), Pokemon Crystal (GBC), Fire Emblem, Pokemon Emerald (GBA), Pokemon Fire Red (GBA).
I tested it on iPhone for the following browsers: Safari, FireFox, Chrome, Brave, Puffin
Device info: iPhone is an iPhone 7 and iPad is an iPad Air 2

Hopefully that helps, this is a really great project!

**Comment by nserup** [comment]
i agree with the problem. And there is no settings of safari that will help to fix the problem. 
I have an iphone X, and run ios 13.3.1 No sound in safari, chrome, edge, firefox. And i ran through settings without finding anything that disables sound.

**Comment by naturiagod** [comment]
iPhone XS no sound

**Comment by magnetardev** [comment]
Fixed in v2.2, which is now released!
