### ISSUE TITLE
Cannot link to Google Drive

### ISSUE THREAD

**Issue by Jenna3715** [iGBAEmu/EclipseIssues#38]
# Description

Attempting to link to a google drive account results in a 400 error "redirect_uri_mismatch". 

# How to Reproduce

Tap on the gear, tap on "linked applications", then tap on "google drive".

# Device Information

Safari on iPhone 7 with iOS 12.3.1
Eclipse version: 2.0.8

**Comment by Majinsmash** [comment]
Fixed in v2.1
