### ISSUE TITLE
Google Drive OAUTH Failure

### ISSUE THREAD

**Issue by clay584** [iGBAEmu/EclipseIssues#49]
# Description

Issues connecting to Google Drive using web-based emulator at http://eclipseemu.me/play

# How to Reproduce

Eclipse>Settings>Cloud>Google Drive

Try to connect to Google to authenticate and get OAUTH error.

Error Message:

```
400. That’s an error.

Error: redirect_uri_mismatch

The JavaScript origin in the request, http://eclipseemu.me, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/669073905466-thn1ff4ctf5u6sf6i2reviboml7endl2.apps.googleusercontent.com?project=669073905466 to update the authorized JavaScript origins.

Learn more

Request Details
redirect_uri=storagerelay://http/eclipseemu.me?id=auth253766
response_type=permission id_token
scope=email profile openid https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/drive.appfolder
openid.realm=
client_id=669073905466-thn1ff4ctf5u6sf6i2reviboml7endl2.apps.googleusercontent.com
ss_domain=http://eclipseemu.me
fetch_basic_profile=true
gsiwebsdk=2
```

# Device Information

## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | true | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.6 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | Desktop | 
| User Agent | Mozilla/5.0 (Windows NT 10.0- Win64- x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 | 
| Do Not Track | 1 | 
| Cookies Enabled | true | 
| ServiceWorker Support | false | 
| Languages | en-US,en | 
| Vendor | Google Inc. | 
 | Platform | Win32 |

**Comment by magnetardev** [comment]
This issue happens when you are on HTTP instead of HTTPS. If you are to switch, you'll need to export your backup in settings on the HTTP site, then import it in the HTTPS one.
