### ISSUE TITLE
[IMPORTANT] After updating, Eclipse’s A, B, Start, Select, L, and R don’t work.

### ISSUE THREAD

**Issue by AlexPlayz06** [iGBAEmu/EclipseIssues#51]
# Description

After updating to iOS 13, Eclipse starts acting weird. The start red loading screen seems stretched when you launch it from the home app. After you load up any game, the A, B, Start, a Select, and maybe L and R don’t work. This is frustrating and there is currently no known fix. 

# How to Reproduce

1. Load up Eclipse on any device that is running iOS 13 or above.
2. Open up any game.
3. Attempt to press buttons A, B, Select, Start, L, and R to see if it processes the press.

# Device Information

I used the built in Safari on iOS 13, added Eclipse to home screen, launched game and it didn’t work. I have an iPad 5 generation.

**Comment by HalfHeartowo** [comment]
same issue, if the team could at least tell us a release date for a new hot fix, I’d be fine with that, but they’ve given us no detail on progress

**Comment by doomsboygaming** [comment]
The Bug Might Be Occurring due to the fact that the new Safari on IOS 13 or IPadOS does not support database creation, or at least database memory expansion. That may not be the issue, but this information may be useful later on.

**Comment by AlexPlayz06** [comment]
It might be, I just hope they see the reports and attempt to fix it. Or at least tell us they are doing something.

**Comment by AlexPlayz06** [comment]
I found something might be important 

Fatal windowing error: "null is not an object (evaluating 'oElement.attachEvent')" file:undefined line: undefined 2

I found it in the web inspector.

**Comment by doomsboygaming** [comment]
The said “invalid” object might be the unresponsive controls, so in return when you try and use the said “controls” then because it is unresponsive it does not send the script to move or control the characters or manipulate the emulator

**Comment by AlexPlayz06** [comment]
Well it’s fixed lol, it was an Apple issue. Update to iOS 13.2 and it fixes the problem.

**Comment by Shugabuga** [comment]
Reopening. If it doesn't work on one version, it's a bug.

Noting updating as a remedy.

**Comment by Shugabuga** [comment]
I'm moving further discussion of this issue to issue #45, as it was opened first.
