### ISSUE TITLE
Glitching display after reopening game

### ISSUE THREAD

**Issue by AShen4467** [iGBAEmu/EclipseIssues#53]
When opening a ROM after closing another one the screen glitches.

Open any ROM
close it
Reopen the same game or another game
The screen then starts to glitch

# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | false | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | true | 
| Skins Setup | true | 
| Eclipse Version | 2.1.6 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | Desktop | 
| User Agent | Mozilla/5.0 (Windows NT 10.0- Win64- x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 | 
| Do Not Track | 1 | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-US,en | 
| Vendor | Google Inc. | 
 | Platform | Win32 |

**Comment by magnetardev** [comment]
This should be addressed in v2.1.8
