### ISSUE TITLE
"Create Backup" broken on iPhone/iOS

### ISSUE THREAD

**Issue by JanJastrow** [iGBAEmu/EclipseIssues#54]
# Description

I'm trying to export my settings/save games with the build-in function "Create Backup", but I'm running into issues.
It shows an <input> field with the json data to copy, but there are multiple problems:
- It's very hard to copy everything since iOS does not mark everything if you tap inside the input box (it only selects from the end to the first forward-slash) -- maybe some JS would help to select everything
- The **data is incomplete**. It seems like there is a 1000 character limit for the data in an input box, so it's impossible to export the data.
(at least my data is incomplete (json) and it would not let me import the data on a desktop browser; also my data is exactly 1000 characters, which is unlikely to be an coincident.)
Maybe there is another way to display/download the data like with a <textarea> or <a href"…" download>

# How to Reproduce

Settings -> Storage -> Create Backup

# Device Information

iPhone Xs
iOS 13.2.3
Safari (but used as an PWA)

**Comment by allweinz88** [comment]
I’m having the same issue. Any updates on this?

**Comment by nserup** [comment]
i am having the same issue.  
iphone x 13.3.1, using safari. 
The export backup, only contains a fraction of the characters needed in safari. 
I am therefore stuck, with playing from safari on my phone. I would very much like to transfer it to my pc, so i can sit better, and use real keyboad buttons. 

This is not the case in chrome or firefox. But in chrome and firefox, there is some issues regarding copying the data, and i cannot save the generated file, from chrome or firefox.

**Comment by LeBloodie** [comment]
im getting the exact same problem any updates would be highly appreciated

**Comment by Shugabuga** [comment]
This issue was fixed in v2.2.
