### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by bluemanta05** [iGBAEmu/EclipseIssues#6]
After i installed eclipse and loaded my old igba files i saw a update than i clicked it and this showed up
![57d2f4e2-eee3-4eab-b460-d96f66fb209a](https://user-images.githubusercontent.com/28136846/36354362-6e939fc8-14d3-11e8-966c-0435c4a9d65e.png)

**Comment by Shugabuga** [comment]
Can you test it now? @Majinsmash pushed an update that might have fixed it (removed cacheKey).

**Comment by bluemanta05** [comment]
It worked

**Comment by bluemanta05** [comment]
Do i need to close it now?

**Comment by Shugabuga** [comment]
Yes.
