### ISSUE TITLE
Save file was completely deleted unexpectedly 

### ISSUE THREAD

**Issue by errordetect0rr** [iGBAEmu/EclipseIssues#64]
I was playing Pokemon Emerald today and I decided to stop playing for a while. Naturally, I saved the game (ingame and emulator) and closed Eclipse. However, when I opened Eclipse again, my library was completely empty and when I added Emerald again, my 9 hour save file was deleted. I didn’t delete Eclipse or clear my history, so I’d like to know whether it’s possible if I can recover the save files for all the saved data.
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.8 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhone | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | false | 
| Languages | en-US | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by magnetardev** [comment]
Maybe you switched from http to https (or vice versa)? That’s the only possible explanation I have... 

Today/yesterday’s update didn’t do anything that would cause this...

**Comment by errordetect0rr** [comment]
Duplicate of #

> Maybe you switched from http to https (or vice versa)? That’s the only possible explanation I have...
> 
> Today/yesterday’s update didn’t do anything that would cause this...

I just checked your theory by changing it to https and changing back to http, but it didn’t seem to have the old save file on either. It seemed to be the only save file that deleted (i had a FireRed save file but it was still there)

**Comment by errordetect0rr** [comment]
It happened about two more times, and it’s really annoying. It happens (sometimes) when I close the app tab.

**Comment by magnetardev** [comment]
Real sorry about the save data not actually getting stored :/

I'm going to add more indication of when saving is occurring and when it ends so there is less confusion, because this is a definite issue and there is no code anywhere that would cause the save data to just disappear like that. 

For now I guess just wait a couple of seconds after tapping save (or exit the game before quitting and then wait a few seconds before closing the tab).

**Comment by errordetect0rr** [comment]
Alright, thanks for the help.
