### ISSUE TITLE
Eclipse has a blue tab color on Google Chrome

### ISSUE THREAD

**Issue by Banakin** [iGBAEmu/EclipseIssues#7]
In Google Chrome on my OnePlus 5T the tab is blue, this is not a major bug but it is slightly annoying and easy to fix by modifying/removing a tag. But it would be nice to see this fixed or implemented in OpenSkin.

**Comment by Shugabuga** [comment]
> OpenSkin

Now that's an interesting idea, but I don't know when Chrome checks for meta tags: on launch or when closing the tab.

**Comment by Shugabuga** [comment]
The core issue has been fixed, but I am almost certain that the relevant meta tag is gathered at launch, so OpenSkin integration is impossible without PHP (which will not happen).
