### ISSUE TITLE
Cheat code support (such as Action Replay and GameShark)

### ISSUE THREAD

**Issue by skullkrusher567** [iGBAEmu/EclipseIssues#74]
Just as the title states I would like to request a feature to input cheat codes . 

love playing gen 3 Pokémon games and which is why I got eclipse for , but sometimes when you gotta grind to be able to beat the next gym leader or elite 4 it takes awhile . That's why I love the infinite rare candy cheat so if you guys could allow us to input cheats that that would be awesome.

**Comment by moonslayer57** [comment]
The one thing missing from the emulator is cheat support

**Comment by Shugabuga** [comment]
Duplicate of #74.

**Comment by chadillac13** [comment]
Are they ever going to make a cheat option??

**Comment by jamesmathews7** [comment]
We need cheat options please I’m begging u
