### ISSUE TITLE
No pasting repo URLs

### ISSUE THREAD

**Issue by Banakin** [iGBAEmu/EclipseIssues#8]
When I have a url on my clipboard I am not able to paste it into the textboxes in eclipse. Im not sure why this issue happens but I am using a OnePlus 5T on the latest Android Oreo Beta.

**Comment by Majinsmash** [comment]
Worked fine on iOS, guessing its a problem with Android.

**Comment by Banakin** [comment]
My thought is that it might be an Fw7 issue and i also haven't tested it thoroughly.

**Comment by Shugabuga** [comment]
I have an Android device I will test it on later.

**Comment by Banakin** [comment]
I think but honestly it's been a while since I tried

**Comment by Shugabuga** [comment]
Okay.

**Comment by Banakin** [comment]
The problem still exists although I'm not quite sure if I'm running Eclipse 2. But I've tested this and I get the same issue in PricePoint. I think it's an issue with fw7.

**Comment by Majinsmash** [comment]
Closing because it's a stale issue. Reopen if it's still prevalent.
