### ISSUE TITLE
Game won’t save

### ISSUE THREAD

**Issue by Bluedudepro** [iGBAEmu/EclipseIssues#83]
I was playing a game and it didn’t save when I pressed the save button, so I thought it might have been something wrong with what I had downloaded so I tried other games but none of my them would save so then I checked to see if it was something with my iPhone but it didn’t save on my iPad either. Please fix this because it’s really annoying to have to start a game from the start every time.

**Comment by arrofacttt** [comment]
Yea

**Comment by Shugabuga** [comment]
Are you using the in-game save feature too?

Duplicate of #60.

**Comment by xXIDarkIXx** [comment]
This did not work
