### ISSUE TITLE
How do I put a gba.sav file in the emulator?

### ISSUE THREAD

**Issue by minedude21** [iGBAEmu/EclipseIssues#84]
# Description

(I would like the feature to change a save I have been playing a Pokémon ruby game and just made a gba.sav file with lots of Pokémon but I would like to add it to the eclipse emulator but idk how or if there is not a way I would like you to please add this feature, thanks)

# IPhone XR

(Safari browser)

**Comment by Shugabuga** [comment]
`.sav` support will be added in v2.2.

**Comment by minedude21** [comment]
Ok thank you so much I can’t wait to use my save form my ds

**Comment by minedude21** [comment]
Also when will v2.2 come out?
