### ISSUE TITLE
Rom is slow 

### ISSUE THREAD

**Issue by maniac409** [iGBAEmu/EclipseIssues#90]
Playing Pokémon crustal Kaizo and it’s super slow. Any idea why ?
# Description

(Please describe your issue or feature request, in detail, here.)

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by hankright22** [comment]
Rom will slow down when in low power mode using an iphone

**Comment by Shugabuga** [comment]
Eclipse does not recommend using Low Power Mode or devices older than the 6S. Please disable Low Power Mode if you use it.

**Comment by Shugabuga** [comment]
Also, please continue discussion in issue #81. It helps us organize unique issues in a sea of duplicates.
