### ISSUE TITLE
Bluetooth controller playability 

### ISSUE THREAD

**Issue by richie22456** [iGBAEmu/EclipseIssues#93]
# Description 
I was just wondering if you could add a feature that would let you use a Bluetooth controller to play the games on the application 

# How to Reproduce

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by Shugabuga** [comment]
Duplicate of #92.
